### ISSUE TITLE
BabelProcessor#process causes java.lang.CloneNotSupportedException

### ISSUE THREAD

**Issue by yuki-takei** [errbuddy/babel-asset-pipeline#7]
## How to reproduce?
1. Grails 3.0.9
2. use `'net.errbuddy.plugins:babel-asset-pipeline:1.4.2'`
3. add configuration only the following line

```
grails.asset.babel.enabled = true
```

(don't set `grails.assets.babel.options`)
## What is it caused?

You'll get:

```
java.lang.IllegalStateException: Calling Context.exit without previous Context.enter
    at org.mozilla.javascript.Context.exit(Context.java:426) ~[rhino-1.7R4.jar:1.7R4]
    at org.mozilla.javascript.Context$exit$14.call(Unknown Source) ~[na:na]
    at asset.pipeline.babel.BabelProcessor.process(BabelProcessor.groovy:78) ~[babel-asset-pipeline-1.4.2.jar:na]
    at asset.pipeline.AbstractAssetFile.processedStream(AbstractAssetFile.groovy:160) ~[asset-pipeline-core-2.6.9.jar:na]
    at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:307) ~[asset-pipeline-core-2.6.9.jar:na]
    at asset.pipeline.DirectiveProcessor$fileContents$1.call(Unknown Source) ~[na:na]
    at asset.pipeline.AssetPipeline.serveUncompiledAsset(AssetPipeline.groovy:65) ~[asset-pipeline-core-2.6.9.jar:na]
    at asset.pipeline.AssetPipelineFilter.doFilterInternal(AssetPipelineFilter.groovy:177) ~[asset-pipeline-3.0.15.jar:na]

(snip)
```

This is caused because of [BabelProcessor.groovy#L60](https://github.com/errbuddy/babel-asset-pipeline/blob/release-1.4.1/src/main/groovy/asset/pipeline/babel/BabelProcessor.groovy#L60).

This line throws a `java.lang.CloneNotSupportedException` when you don't set `grails.assets.babel.options`. However, the exception is abandoned by an `java.lang.IllegalStateException` that is thrown in [the following finally block](https://github.com/errbuddy/babel-asset-pipeline/blob/release-1.4.1/src/main/groovy/asset/pipeline/babel/BabelProcessor.groovy#L78).

**Comment by yuki-takei** [comment]
A temporary solution is using 1.3.0 or set `grails.assets.babel.options`.

**Comment by peh** [comment]
hey @yuki-takei can you check with 1.4.3 please.

**Comment by yuki-takei** [comment]
@peh
I confirmed to work successfully. Good Job!
